---
- name: Prepare IMC MySQL server
  hosts: imcmysql
  remote_user: root
  roles:
    - common
    - dbserver

- name: Prepare IMC server
  hosts: imcapp
  remote_user: root
  roles:
    - common
    - imcserver
