---
# Handler to handle DB tier notifications

- name: restart iptables
  service: name=iptables state=restarted
  become: true

- name: restart mysql
  service: name=mysqld state=restarted
  become: true
