---
- name: Prepare IMC MySQL server
  hosts: imcmysql
  remote_user: vagrant
  sudo: yes
  roles:
    - common
    - dbserver

- name: Prepare IMC server
  hosts: imcapp
  remote_user: vagrant
  sudo: yes
  roles:
    - common
    - imcserver
