---
- name: Prepare IMC MySQL server
  hosts: imcmysql
  become: root
  roles:
    - common
    - dbserver

- name: Prepare IMC server
  hosts: imcapp
  become: root
  roles:
    - common
    - imcserver
